# This is a basic workflow to help you get started with Actions

name: Deploy to Nginx Server

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    # Tests against node version
    strategy: 
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
        working-directory: ./src
      - run: npm run tsc
        working-directory: ./src
      - run: npm run start
        working-directory: ./src
